//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Word2007RedactionTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Word2007RedactionTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word 2007 Redaction Tool.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; &amp;Less.
        /// </summary>
        internal static string ButtonLess {
            get {
                return ResourceManager.GetString("ButtonLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;More &gt;&gt;.
        /// </summary>
        internal static string ButtonMore {
            get {
                return ResourceManager.GetString("ButtonMore", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Delete16 {
            get {
                object obj = ResourceManager.GetObject("Delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Mark.
        /// </summary>
        internal static string FindAndMarkLabel {
            get {
                return ResourceManager.GetString("FindAndMarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and mark specific text within the document..
        /// </summary>
        internal static string FindAndMarkSupertip {
            get {
                return ResourceManager.GetString("FindAndMarkSupertip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Mark16 {
            get {
                object obj = ResourceManager.GetObject("Mark16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string MarkKeytip {
            get {
                return ResourceManager.GetString("MarkKeytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        internal static string MarkLabel {
            get {
                return ResourceManager.GetString("MarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        internal static string MarkScreentip {
            get {
                return ResourceManager.GetString("MarkScreentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to access other other options such as redacting all marked regions in the document..
        /// </summary>
        internal static string MarkSplitMenuSupertip {
            get {
                return ResourceManager.GetString("MarkSplitMenuSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark the selected text. When the document is redacted, the text will be replaced..
        /// </summary>
        internal static string MarkSupertip {
            get {
                return ResourceManager.GetString("MarkSupertip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Next16 {
            get {
                object obj = ResourceManager.GetObject("Next16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NR.
        /// </summary>
        internal static string NextKeytip {
            get {
                return ResourceManager.GetString("NextKeytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextLabel {
            get {
                return ResourceManager.GetString("NextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Mark.
        /// </summary>
        internal static string NextScreentip {
            get {
                return ResourceManager.GetString("NextScreentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the next redaction mark in the document..
        /// </summary>
        internal static string NextSupertip {
            get {
                return ResourceManager.GetString("NextSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no redaction marks in the current document..
        /// </summary>
        internal static string NoRedactionMarks {
            get {
                return ResourceManager.GetString("NoRedactionMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  occurrence found and marked..
        /// </summary>
        internal static string OccurrenceFound {
            get {
                return ResourceManager.GetString("OccurrenceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  occurrences found and marked..
        /// </summary>
        internal static string OccurrencesFound {
            get {
                return ResourceManager.GetString("OccurrencesFound", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Previous16 {
            get {
                object obj = ResourceManager.GetObject("Previous16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VR.
        /// </summary>
        internal static string PreviousKeytip {
            get {
                return ResourceManager.GetString("PreviousKeytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PreviousLabel {
            get {
                return ResourceManager.GetString("PreviousLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Mark.
        /// </summary>
        internal static string PreviousScreentip {
            get {
                return ResourceManager.GetString("PreviousScreentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the previous redaction mark in the document..
        /// </summary>
        internal static string PreviousSupertip {
            get {
                return ResourceManager.GetString("PreviousSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redact.
        /// </summary>
        internal static string RedactGroupLabel {
            get {
                return ResourceManager.GetString("RedactGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered while redacting this document..
        /// </summary>
        internal static string RedactionFailed {
            get {
                return ResourceManager.GetString("RedactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redact all marked regions within the current document..
        /// </summary>
        internal static string RedactMenuItemDescription {
            get {
                return ResourceManager.GetString("RedactMenuItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redact Document.
        /// </summary>
        internal static string RedactMenuItemLabel {
            get {
                return ResourceManager.GetString("RedactMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redact Document.
        /// </summary>
        internal static string RedactScreentip {
            get {
                return ResourceManager.GetString("RedactScreentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redact all marked regions within the current document. The resulting document will be shown in a new window..
        /// </summary>
        internal static string RedactSupertip {
            get {
                return ResourceManager.GetString("RedactSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string ReviewTab {
            get {
                return ResourceManager.GetString("ReviewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue searching from the beginning of the document?.
        /// </summary>
        internal static string SearchFromBeginning {
            get {
                return ResourceManager.GetString("SearchFromBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue searching from the end of the document?.
        /// </summary>
        internal static string SearchFromEnd {
            get {
                return ResourceManager.GetString("SearchFromEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified text was not found in the document..
        /// </summary>
        internal static string TextNotFound {
            get {
                return ResourceManager.GetString("TextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Marks.
        /// </summary>
        internal static string UnmarkAllLabel {
            get {
                return ResourceManager.GetString("UnmarkAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK.
        /// </summary>
        internal static string UnmarkKeytip {
            get {
                return ResourceManager.GetString("UnmarkKeytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmark.
        /// </summary>
        internal static string UnmarkLabel {
            get {
                return ResourceManager.GetString("UnmarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmark.
        /// </summary>
        internal static string UnmarkScreentip {
            get {
                return ResourceManager.GetString("UnmarkScreentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to access other options such as removing all redaction marks from the document..
        /// </summary>
        internal static string UnmarkSplitMenuSupertip {
            get {
                return ResourceManager.GetString("UnmarkSplitMenuSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmark the selected text..
        /// </summary>
        internal static string UnmarkSupertip {
            get {
                return ResourceManager.GetString("UnmarkSupertip", resourceCulture);
            }
        }
    }
}
